### ISSUE TITLE
Buttons are not  properly displayed.

### ISSUE THREAD

**Issue by Pineirin** [inveniosoftware/invenio-theme#335]
The text value and the icon of some buttons seem to be horizontally misaligned.
![Screenshot from 2022-10-26 17-58-40](https://user-images.githubusercontent.com/25476209/198228757-a6b03cf9-4799-468a-b80c-36fb2e65f774.png)
![Screenshot from 2022-10-26 18-00-21](https://user-images.githubusercontent.com/25476209/198228764-3a8cd888-9064-4959-99f2-84b949e74bd4.png)
Screenshots taken from the My dashboard (uploads, requests) part of invenio-app-rdm.

A potential solution was proposed by @jennur (to be tested).
![image](https://user-images.githubusercontent.com/25476209/198229221-15a118d8-b639-42f5-bb0a-af29bbf86902.png)

**Comment by jennur** [comment]
Just to clear up, I was not suggesting a solution to the icon-misalignment, but the horizontal text-alignment. To illustrate, the difference in padding between the combo `.fluid.labeled` and `.labeled`-only:


![Image](https://user-images.githubusercontent.com/21052053/198273073-2d72042f-adec-44e6-b366-2edb6aba95ea.png)

My suggestion to solve this issue is to add the following to `button.overrides`, to make sure the labeled button has the same padding even if fluid, to align the button text nicely.:

```
.ui.labeled.icon.button.fluid {
  padding-left: @labeledIconPadding !important;
}
```

**Comment by ppanero** [comment]
there one PR still not merged
